### ISSUE TITLE
Suggestion of improvements  

### ISSUE THREAD

**Issue by Czaki** [noprobelm/tempy#6]
In the beginning, I will appreciate your job. 

There is no information about the contribution so I write Issue. 

At first, cloning using ssh requires permission to repository. So instead of 

```bash
git clone git@github.com:noprobelm/tempy.git && cd tempy
```
there should be 

```bash
git clone https://github.com/noprobelm/tempy.git
```

But pip allows installing directly from the git repository 

so there is no need to clone, one could just call: 

```bash
pip install git+https://github.com/noprobelm/tempy
```

It will be also nice if the configuration file will allow defining default locations and units. 

Thanks for a really nice package.

**Comment by noprobelm** [comment]
Thanks for your suggestions. You're right, `https` should be used over `ssh`. I simplified the installation procedure to utilize pip's ability to install from a remote repository. Thanks for that.

I created issue #9 to manage adding extended config options. Closing this issue.
